### ISSUE TITLE
Nodejs: Errors profiling

### ISSUE THREAD

**Issue by jorgeperezc** [grafana/pyroscope#1568]
Hello, I was trying to implement your solution in pull mode in Nodejs with version 18.9.0 but I get this stack trace:
```
Error collecting memory profile Error: Heap profiler is not enabled.
    at v8Profile (/test/node_modules/pprof/out/src/heap-profiler.js:32:15)
    at Object.profile (/test/node_modules/pprof/out/src/heap-profiler.js:46:20)
    at Object.collectHeap (/test/node_modules/@pyroscope/nodejs/dist/cjs/index.js:192:32)
    at Object.memory_profile (/test/endpoints/memory_profile_endpoint.js:6:31)
    at preHandlerCallback (/test/node_modules/fastify/lib/handleRequest.js:126:28)
    at preValidationCallback (/test/node_modules/fastify/lib/handleRequest.js:110:5)
    at handler (/test/node_modules/fastify/lib/handleRequest.js:74:7)
    at handleRequest (/test/node_modules/fastify/lib/handleRequest.js:22:5)
    at runPreParsing (/test/node_modules/fastify/lib/route.js:496:5)
    at next (/test/node_modules/fastify/lib/hooks.js:168:7)
```
I use the latest version of pprof and the pyroscope library.

Does it sound like I may be doing something wrong?

Thank you very much.

**Comment by eh-am** [comment]
Hey! Sorry getting back to you after so long.

Assuming (from your stacktrace) that you are running `fastify`, and therefore not using the Express Middleware we have.

So based on the implementation (and the error message), the `Heap` profiler needs to be initialized. So you need to call `  Pyroscope.startHeapCollecting()` (
https://github.com/pyroscope-io/pyroscope-nodejs/blob/09d3f4d1b77d8640181e871db0fa3d60919e4a7d/src/express.ts#L36)

But this is just a guess, more info and maybe a reproducible example could help us trying to find the cause.
