### ISSUE TITLE
Change the default storage directory

### ISSUE THREAD

**Issue by alonlong** [grafana/pyroscope#186]
```
~/Project/go/src/pyroscope/bin|main ⇒  ./pyroscope server
panic: mkdir /var/lib/pyroscope: permission denied

goroutine 1 [running]:
github.com/pyroscope-io/pyroscope/pkg/cli.startServer(0xc0001d4780)
        github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:369 +0x825
github.com/pyroscope-io/pyroscope/pkg/cli.generateRootCmd.func1(0x4e42a70, 0xc000138008, 0xc00013e010, 0x0, 0x0, 0xc0001b1e30, 0x45903fb)
        github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:304 +0x5f
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc0001922c0, 0x4e42a70, 0xc000138008, 0x0, 0x0)
        github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:153 +0x1b2
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc000192630, 0x4e42a70, 0xc000138008, 0x0, 0x0)
        github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:157 +0x125
github.com/peterbourgon/ff/v3/ffcli.(*Command).ParseAndRun(0xc000192630, 0x4e42a70, 0xc000138008, 0xc00013e010, 0x1, 0x1, 0x1, 0xc0001d4780)
        github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:169 +0x85
github.com/pyroscope-io/pyroscope/pkg/cli.Start(0xc0001d4780, 0xc0001d4780, 0xc000038800)
        github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:362 +0x98
main.main()
        github.com/pyroscope-io/pyroscope/cmd/pyroscope/main.go:13 +0x4d
```
**Problem Description:** When i start the server with normal user, it happens an error like this. I think it's because pyroscope use the '/var/lib/pyroscope' as the default storage directory which needs more permissions for reading and writing. 

**Question:** Is it better to change the default storage directory to a normal one like '$HOME/.pyroscope', i think it's better for any user without caring about the permissions of storage directory  with any account~

**Comment by juligreen** [comment]
Duplicate: [181](https://github.com/pyroscope-io/pyroscope/issues/181)
