### ISSUE TITLE
Panic in the frontend

### ISSUE THREAD

**Issue by cyriltovena** [grafana/pyroscope#2179]
Found this one today:

```


2023-07-27 09:05:00.773	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa52023-07-27 09:05:00.773created by golang.org/x/sync/errgroup.(*Group).Go2023-07-27 09:05:00.773	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x642023-07-27 09:05:00.773golang.org/x/sync/errgroup.(*Group).Go.func1()2023-07-27 09:05:00.773	github.com/grafana/pyroscope/pkg/frontend/frontend_select_merge_stacktraces.go:64 +0x21c2023-07-27 09:05:00.773github.com/grafana/pyroscope/pkg/frontend.(*Frontend).SelectMergeStacktraces.func1()2023-07-27 09:05:00.773	github.com/grafana/pyroscope/pkg/model/flamegraph.go:199 +0x1962023-07-27 09:05:00.773github.com/grafana/pyroscope/pkg/model.(*FlameGraphMerger).MergeFlameGraph(0xc000459000, 0xc000162150)2023-07-27 09:05:00.773	github.com/grafana/pyroscope/pkg/model/flamegraph.go:240 +0x2db2023-07-27 09:05:00.773github.com/grafana/pyroscope/pkg/model.buildStack({0xc0004e6900?, 0x180090?, 0xc0004e6900?}, 0xc000162150, 0x2, 0x4ed55e0?)2023-07-27 09:05:00.773goroutine 4961128 [running]:2023-07-27 09:05:00.773 | 2023-07-27 09:05:00.773 | golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5 |   |   |   | 2023-07-27 09:05:00.773 | created by golang.org/x/sync/errgroup.(*Group).Go |   |   |   | 2023-07-27 09:05:00.773 | golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64 |   |   |   | 2023-07-27 09:05:00.773 | golang.org/x/sync/errgroup.(*Group).Go.func1() |   |   |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/frontend/frontend_select_merge_stacktraces.go:64 +0x21c |   |   |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/frontend.(*Frontend).SelectMergeStacktraces.func1() |   |   |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/model/flamegraph.go:199 +0x196 |   |   |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/model.(*FlameGraphMerger).MergeFlameGraph(0xc000459000, 0xc000162150) |   |   |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/model/flamegraph.go:240 +0x2db |   |   |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/model.buildStack({0xc0004e6900?, 0x180090?, 0xc0004e6900?}, 0xc000162150, 0x2, 0x4ed55e0?) |   |   |   | 2023-07-27 09:05:00.773 | goroutine 4961128 [running]: |   |   |   | 2023-07-27 09:05:00.773 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2023-07-27 09:05:00.773 | golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5 |  
  |   | 2023-07-27 09:05:00.773 | created by golang.org/x/sync/errgroup.(*Group).Go |  
  |   | 2023-07-27 09:05:00.773 | golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64 |  
  |   | 2023-07-27 09:05:00.773 | golang.org/x/sync/errgroup.(*Group).Go.func1() |  
  |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/frontend/frontend_select_merge_stacktraces.go:64 +0x21c |  
  |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/frontend.(*Frontend).SelectMergeStacktraces.func1() |  
  |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/model/flamegraph.go:199 +0x196 |  
  |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/model.(*FlameGraphMerger).MergeFlameGraph(0xc000459000, 0xc000162150) |  
  |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/model/flamegraph.go:240 +0x2db |  
  |   | 2023-07-27 09:05:00.773 | github.com/grafana/pyroscope/pkg/model.buildStack({0xc0004e6900?, 0x180090?, 0xc0004e6900?}, 0xc000162150, 0x2, 0x4ed55e0?) |  
  |   | 2023-07-27 09:05:00.773 | goroutine 4961128 [running]: |  
  |   | 2023-07-27 09:05:00.773 |   |  

2023-07-27 09:05:00.773panic: runtime error: index out of range [-1] |   |   | 2023-07-27 09:05:00.773 | panic: runtime error: index out of range [-1]
  |   | 2023-07-27 09:05:00.773 | panic: runtime error: index out of range [-1]



```

cc @kolesnikovae

**Comment by kolesnikovae** [comment]
Thanks for reporting it – I'll take a look today. Which version are you running?
