### ISSUE TITLE
maven dependency have some problems

### ISSUE THREAD

**Issue by xiaodunxin** [grafana/pyroscope#2216]
#### Describe the bug

start fail

#### To Reproduce

1. Start Java Demo

#### Expected behavior

success

#### Environment

- jdk 8 
- groupId io.pyroscope
- artifactId agent
- version 0.11.5

![image](https://github.com/grafana/pyroscope/assets/58406805/8bbce145-08d4-4d78-83ea-5982ff29e9be)

#### Additional Context

java.lang.ExceptionInInitializerError: null
	at io.pyroscope.javaagent.Profiler.<init>(Profiler.java:26) ~[agent-0.11.5.jar:na]
	at io.pyroscope.javaagent.PyroscopeAgent$Options$Builder.<init>(PyroscopeAgent.java:78) ~[agent-0.11.5.jar:na]
	at io.pyroscope.javaagent.PyroscopeAgent.start(PyroscopeAgent.java:32) ~[agent-0.11.5.jar:na]
	at com.example.maven_demo.init.InitService.run(InitService.java:48) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759) [spring-boot-2.7.13.jar:2.7.13]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749) [spring-boot-2.7.13.jar:2.7.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.7.13.jar:2.7.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.7.13.jar:2.7.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.7.13.jar:2.7.13]
	at com.example.maven_demo.MavenDemoApplication.main(MavenDemoApplication.java:10) [classes/:na]
Caused by: java.lang.RuntimeException: Unsupported OS Windows 8.1
	at io.pyroscope.labels.io.pyroscope.PyroscopeAsyncProfiler.libraryFileName(PyroscopeAsyncProfiler.java:108) ~[agent-0.11.5.jar:na]
	at io.pyroscope.labels.io.pyroscope.PyroscopeAsyncProfiler.deployLibrary(PyroscopeAsyncProfiler.java:41) ~[agent-0.11.5.jar:na]
	at io.pyroscope.labels.io.pyroscope.PyroscopeAsyncProfiler.<clinit>(PyroscopeAsyncProfiler.java:25) ~[agent-0.11.5.jar:na]
	... 10 common frames omitted
![image](https://github.com/grafana/pyroscope/assets/58406805/1591e5e2-65bf-41e4-b1c9-e1aacc333ffd)

```[tasklist]
### Tasks
```

**Comment by korniltsev** [comment]
Exception says Unsupported OS Windows 8.1
