### ISSUE TITLE
NodeJS example with docker have node-gyp errors

### ISSUE THREAD

**Issue by davigottt** [grafana/pyroscope#3646]
#### Describe the bug
U can't run node example with the provided dockerfile

#### To Reproduce

1. Go into any node example
2. docker compose build
3. docker compose up -d
4. check logs  and
```bash
 /app/node_modules/node-gyp-build/index.js:59
2024-10-22T15:15:43.328348158Z   throw new Error('No native build was found for runtime=' + runtime + ' abi=' + abi + ' platform=' + platform + libc + ' arch=' + arch)
2024-10-22T15:15:43.328356404Z         ^
2024-10-22T15:15:43.328359920Z 
2024-10-22T15:15:43.328363557Z Error: No native build was found for runtime=node abi=131 platform=linuxglibc arch=x64
2024-10-22T15:15:43.328367214Z     at load.path (/app/node_modules/node-gyp-build/index.js:59:9)
2024-10-22T15:15:43.328370250Z     at load (/app/node_modules/node-gyp-build/index.js:19:30)
2024-10-22T15:15:43.328373296Z     at Object.<anonymous> (/app/node_modules/@datadog/pprof/out/src/heap-profiler-bindings.js:44:18)
2024-10-22T15:15:43.328376792Z     at Module._compile (node:internal/modules/cjs/loader:1568:14)
2024-10-22T15:15:43.328380209Z     at Object..js (node:internal/modules/cjs/loader:1711:10)
2024-10-22T15:15:43.328383215Z     at Module.load (node:internal/modules/cjs/loader:1328:32)
2024-10-22T15:15:43.328386251Z     at Function._load (node:internal/modules/cjs/loader:1138:12)
2024-10-22T15:15:43.328389427Z     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
2024-10-22T15:15:43.328392442Z     at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
2024-10-22T15:15:43.328395498Z     at Module.require (node:internal/modules/cjs/loader:1350:12)
```

#### Expected behavior

Application starts normally

#### Environment

- Infrastructure: Fedora 40, provided dockerfile
- Deployment tool: Docker

**Comment by richard-julien** [comment]
Hi, any available configuration, workaround available? thanks

**Comment by richard-julien** [comment]
Ok so after some research, if it can help some people,
The prebuilt exists in the package but the loader try to load them from the root of your project.
So you need to copy node_modules\@datadog\pprof\prebuilds inside project_dir\prebuilds

**Comment by korniltsev** [comment]
This should have been fixed with https://github.com/grafana/pyroscope-nodejs/commit/54777ab46a1a9aa8bfcc93335f22b0acaf57549e 

Does it still not work with [v0.4.3](https://github.com/grafana/pyroscope-nodejs/releases/tag/v0.4.3)
[v0.4.2](https://github.com/grafana/pyroscope-nodejs/releases/tag/v0.4.2) versions?

**Comment by tangirmiah** [comment]
> This should have been fixed with [grafana/pyroscope-nodejs@54777ab](https://github.com/grafana/pyroscope-nodejs/commit/54777ab46a1a9aa8bfcc93335f22b0acaf57549e)
> 
> Does it still not work with [v0.4.3](https://github.com/grafana/pyroscope-nodejs/releases/tag/v0.4.3) [v0.4.2](https://github.com/grafana/pyroscope-nodejs/releases/tag/v0.4.2) versions?

even after updating to v0.4.3 we are still facing the same error
